<?php

/**
 * @file
 */

/**
 * Helper function
 *
 * @return array
 *   Aeon5 color schemes array
 */
function _aeon5_color_schemes() {
  return array(
    'Original Teal' => array('link' => '688494', 'from' => 'a8d0d4', 'to' => '7a9aa8'),
    'Stellar Blue' => array('link' => '2f427f', 'from' => '8598d5', 'to' => '2f427f'),
    'Tasty Tomato' => array('link' => 'b55254', 'from' => 'cd7b7b', 'to' => 'b55254'),
    'Blue Sky' => array('link' => '5a95cf', 'from' => '63abdb', 'to' => '5a95cf'),
    'Silver Gray' => array('link' => '688494', 'from' => 'c0c0c0', 'to' => 'a3a3a3'),
    'Midnight' => array('link' => '688494', 'from' => '3f3f3f', 'to' => '3d3d3d'),
    'Funky Purple' => array('link' => '763673', 'from' => 'A0789D', 'to' => '763673'),
    'Mint' => array('link' => '688c6e', 'from' => '86af8d', 'to' => '688c6e'),
    'Orange' => array('link' => 'f27334', 'from' => 'ff9764', 'to' => 'f27334'),
    'Cappuccino' => array('link' => '88664a', 'from' => '98826e', 'to' => '88664a'),
  );
}

